### ISSUE TITLE
Adding option for showing logs in apk-generator

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1798] opened 2017-07-09 16:14 UTC
**Actual Behaviour**

Currently the apk generator doesnt show logs incase the apk has some problem in it.

**Expected Behaviour**

Adding logs option so that user can view them in case the apk upload fails

**Would you like to work on the issue?**

-

**Target Milestone to solve the issue**

[Milestone 10](https://github.com/fossasia/open-event-android/milestone/33)

**Comment by mahikaw** [comment] 2017-07-10 15:59
@arp95 Is this issue possibly a duplicate of #1555 ?

**Comment by arp95** [comment] 2017-07-10 16:06
this issue focuses on the ui as well apart from showijg the logs in the generator. 
we can close that issue as of now.

**Closed as completed** 2018-06-01 06:02 UTC
Labels: feature, has-PR
