### ISSUE TITLE
Hardcoded string in upcoming_dialog.xml

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2297] opened 2018-01-31 18:59 UTC
**Actual Behaviour**
Hardcoded "OK" is present

**Expected Behaviour**
It should not be present.

**Steps to reproduce it**
Just a string resource is to be made.

**Would you like to work on it ?**
Yes

**Comment by iamareebjamal** [comment] 2018-01-31 20:09
Please don't create issues with one line fixes. I take that you have been involved in the project and you are not just a beginner, Either cover the whole project and remove hardcoded string or at least a large area of it. Editing single line in a PR which is just a chore, not a bug fix or feature is discouraged for those who are not beginners

**Comment by dreadpool2** [comment] 2018-01-31 20:15
@iamareebjamal I am sorry, I got your point. Should I just close the PR then?

**Comment by iamareebjamal** [comment] 2018-01-31 20:38
If you want to cover the whole project or several files, then please go ahead and if not, change the issue such that it encompasses whole project and if someone may want to take it up, they may

**Comment by codebu5ter** [comment] 2018-02-02 04:53
Hi! Can I take this up? 
This is my first time contributing to this repo, so I'd love to get started with a simple contribution.

**Comment by dreadpool2** [comment] 2018-02-02 05:34
@codebu5ter Yep! go ahead

**Comment by dr0pdb** [comment] 2018-03-30 08:05
@dreadpool2 Please close this. Once we have a lot of hardcoded strings we can open this one up. It is only increasing the number of issues and the issues with higher priority can get ignored due to this.

**Closed as completed** 2018-03-30 09:25 UTC
Labels: has-PR
