### ISSUE TITLE
Implementation of notification.py file in apk-generator

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1800] opened 2017-07-09 18:57 UTC
**Actual Behaviour**

Implementing the code for notifications in apk generator.

**Expected Behaviour**

Doing the above the task.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

-

**Target Milestone to solve the issue**

@niranjan94 please add this.
https://github.com/fossasia/open-event-android/milestone/33

**Comment by arp95** [comment] 2017-07-13 05:45
@niranjan94 
in the notification file there are three types written out of which smtp is already written. do you suggest that code for all three should be written and in send() method i test which method to call depending on the configuration?

**Comment by niranjan94** [comment] 2017-07-13 05:47
@arp95 actually. This issue is a duplicate of https://github.com/fossasia/open-event-android/issues/1601... So closing it now.

**Closed as completed by niranjan94** 2017-07-13 05:47 UTC
