### ISSUE TITLE
Add ViewModel for DayScheduleFragment

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2080] opened 2018-01-01 06:36 UTC
**Actual Behaviour**

There is no viewmodel for DayScheduleFragment

**Expected Behaviour**

There should be a viewmodel.

**Would you like to work on the issue?**
Yes

**Comment by dr0pdb** [comment] 2018-01-01 06:38
@dreadpool2 Before creating an issue, please check if the issue about the same topic already exists.
Duplicate of #2031

**Comment by dreadpool2** [comment] 2018-01-01 06:39
Oh!  I am extremely sorry !! I coudn't find the issue! @srv-twry

**Comment by dr0pdb** [comment] 2018-01-01 06:40
@dreadpool2 No problem :) Kindly close it. If you want , you can work on #2051 . Kindly drop a comment their if you want to go ahead.

**Comment by dreadpool2** [comment] 2018-01-01 06:43
Ok cool! &#128402;&#128402;

**Closed as completed** 2018-01-01 06:43 UTC
Labels: has-PR
