### ISSUE TITLE
Adding feedback functionality under an user

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2299] opened 2018-01-31 19:52 UTC
**Expected Behaviour**
The feedback posting functionality is present in the API [feedback](https://open-event-api.herokuapp.com/#feedback). It would be nice to implement it in the app.

**Would you like to work on the issue?**
 Yes
@iamareebjamal @simarsingh24 your views on this?

**Comment by iamareebjamal** [comment] 2018-01-31 20:38
Duplicate of #2293

**Closed as completed by iamareebjamal** 2018-01-31 20:38 UTC
Labels: duplicate
